<table border="0" cellpadding="0" cellspacing="10" width="100%">
   
   <tr><td bgcolor="#cccccc" background="imagenes/bg_linea_punteada.gif" height="1" colspan="3"></td></tr>
   <tr><td colspan="3"><img src="imagenes/titulo_que_es.gif"></td></tr>
   <tr>
   <td align="center" vAlign="top">       
       <p style="text-align:justify" class="txt11titulo">
Es un Sistema Gr&aacute;fico - Anal&iacute;tico que tiene el objetivo de formar una o varias combinaciones de  n&uacute;meros con posibilidades de ganar, en sorteos o concursos como el <b style="color:'red';">Melate&reg;</b> (en M&eacute;xico ) o similares en otros pa�ses, los concursos  del "<b style="color:'red';">Melate&reg;</b>" se  realizan  dos veces    (una el Mi&eacute;rcoles  y otra el Domingo de cada semana)  y en los que usted puede participar  desde una hasta la cantidad de combinaciones que  quiera. El sorteo consiste  en formar  combinaciones de  seis o mas n&uacute;meros (MODALIDAD M&Uacute;LTIPLE) de una serie de ellos  que van actualmente (del n&uacute;mero 1 al  n&uacute;mero 47 en M&eacute;xico).<br><br>
(Para los sorteos en otros pa&iacute;ses como el <b style="color:blue;">PowerBall&reg;</b> y <b style="color:'#ff9900';">HotLotto&reg;</b>, en  U.S.A., o el <b style="color:'#339900';">Bonoloto&reg;</b>, <b style="color:'#339900';">La Primitiva y El Gordo de La Primitiva&reg;</b> en Espa�a, Y  similares en otros pa&iacute;ses como: Canad&aacute;, Inglaterra, Australia o Argentina esta serie de n&uacute;meros es diferente (en cuanto  a la cantidad  de ellos) pero tambi&eacute;n se juega en forma similar  al   "<b style="color:'red';">Melate&reg;</b>"  de M&eacute;xico (Acertando  a los seis n&uacute;meros naturales  del resultado del sorteo, se es ganador del primer premio, entre otros).<br><br>
<img align="right" hspace="10" src="imagenes/paginaskm07.gif" alt="Skmoney System &reg;">
El sistema  o m&eacute;todo  "<b>SKYMONEY SYSTEM</b> &reg;" esta basado en el comportamiento gr&aacute;fico estad&iacute;stico de los resultados de dicho sorteos , analizando y reduciendo &eacute;ste  resultado  y grafic&aacute;ndolo  para tener un antecedente de su comportamiento  y estableciendo los par&aacute;metros que permitir&aacute;n al usuario o concursante aumentar sus posibilidades de ganar en dichos sorteos  (<b>Al reducir las probabilidades en contra,  del jugador que  participe</b>) y  <b>ubicarlo</b>  en el <b>campo</b> en donde se dan la mayor&iacute;a de las veces los resultados de dichos sorteos, con lo que <b>aumentar&aacute;</b> sus <b>posibilidades</b> de <b>salir ganador</b>.<br><br>

Le proporciona adem&aacute;s  al  jugador participante,  una <b>valiosa herramienta</b> para generar sus m&uacute;ltiples combinaciones con <b>mayores posibilidades</b> en <b>forma autom&aacute;tica</b>, dentro de ese <b>campo</b> (que <b>&eacute;l mismo elige</b>) y est&aacute;  <b>dise&ntilde;ado</b> y <b>patentado</b> por nuestro equipo t&eacute;cnico, espec&iacute;ficamente para ello, <b>con una capacidad que rebasa y por mucho las habilidades y posibilidades del jugador promedio</b>  desde <b>dos combinaciones</b> de <b>6 n&uacute;meros</b>  hasta aproximadamente <b>20,000 combinaciones</b> en forma <b>autom&aacute;tica</b> en <b>menos</b> de <b>90 seg.</b>  (<b>caracter&iacute;stica</b>  que hace a <b>nuestro m&eacute;todo</b> y su <b>generador de combinaciones</b> completamente <b>diferente</b> a <b>otros</b>) <b><i>para lograr tal objetivo ganador</i></b>.
       </p>
   </td>
   </tr>
   <tr><td>&nbsp;</td></tr>	        
</table>