  <tr>
    <td>
       <p class="contedido" style="text-align:justify;">
Como  una  BREVE EXPLICACIÓN del método que le estamos proponiendo y debido al Campo Grande  de  posibilidades en contra  ( ya  indicadas)   y  de acuerdo al análisis del campo  o Banda en donde se han dado dichos resultados, nosotros los seis números naturales  resultantes  en cada sorteo los sumamos  numero a numero  y obtenemos una suma total (La  que graficamos,) para darnos cuenta de las variaciones de dichas sumas y  a  su vez los números que constituyen esta  suma total, también los sumamos uno a uno y obtenemos  un solo numero al que denominamos DIGITO  (Y el  que  también  graficamos)  y  que  por lógica  ira  variando del  1 al  9 , ya  que por ejemplo la suma total  = 134 =1+ 3 + 4 = 8  ( Digito)  o  por ejemplo  la  suma total = 165 = 1+ 6 + 5 = 12 =  1 + 2 =  3 (Digito)       (solo por  mencionar algunas). Lo  anterior nos permite estadística   razonable y gráficamente establecer  parámetros  de variación de c / u de los números, de las Sumas y /o de su correspondiente  Digito, lo   que nos permitirá  seleccionar los números para   una determinada suma  o  digito  y de  acuerdo  a dichas  variaciones establecer   un  pronostico  definido,  ya que de otra manera y siendo un campo tan grande de posibilidades,  si no lo hiciéramos así  estaríamos prácticamente perdidos, pues no sabríamos en donde ubicar nuestra apuesta, ya que para ser  ganador del primer Premio, es necesario que UD. acierte  a los seis números naturales del  resultado  y por lógica  a  su  suma total . Esta  es  la razón  por la que nuestro metodo parte del análisis  de  variación de  los números de las sumas, y/o sus digitos  resultantes , en  dichos sorteos 
<br><br>
NOTA.-  Mas adelante  vera  UD,  la conveniencia  de  establecer    adecuadamente los números de esa  SUMA  TOTAL y/o  su  DIGITO  correspondiente, para  aplicar  su  CALCULADOR   o  GENERADOR DE COMBINACIONES, que le estamos  proponiendo,  el  cual  a  sido especificamente  diseñado  y  automatizado  por  nosotros ,  para  obtener  dichas combinaciones entre los limites numericos que ud. establezca, con posibilidades  ganadoras. ( Desde  2  hasta  varios cientos   o   miles  de  ellas,  en  menos  de  60 segundos, dependiendo del tipo de conexión de cada usuario y/o del trafico de flujo de datos del servidor).  
<br><br>
Y como explicamos, dichos   seis  números, nos dan  un valor total, al   sumarlos  de izquierda  a  Derecha  y  del  de  menor  al   de mayor  valor, al  que  le llamamos SUMA  RESULTANTE. Y como ya indicamos:
<br><br>
1°).- Nosotros   supondremos (Basados en los datos estadísticos) ( y por lo explicado) sumas  resultantes que estén o se encuentren entre los  valores  de  96  y   192  (ya  que  el campo de probabilidades en contra, aumento  al agregarse los números 45,46 y 47) (ver Pág.. 6 )  y  con la ayuda de las Graficas Y Estadísticas de la Variación de Numero a numero y (de izq. a derecha) (Variación grafica  y estadística del 1° numero de la serie), (Variación grafica y estadística del 2° numero de la serie)  etc., y así sucesivamente eligiendo los seis  números que nos den como resultado la suma que PREVIAMENTE hayamos ESCOGIDO,  y procurando que estén) dentro de (los valores indicados arriba) y tomando en cuenta para cada uno de los NUMEROS que estemos SELECCIONANDO su probable variación según su(s) comportamiento(s) estadístico(s) anteriores, esta es una de las  formas que nuestro método SKYMONEY SYSTEM &reg; recomienda (entre otras)  (puede ser a la inversa primero los números), para formar solo una, dos, tres o mas sumas de seis números (con posibilidades ganadoras).(se puede consultar obviamente la grafica de dígitos para esta selección, o  determinado  pronostico pensado)
       </p>
    </td>
  </tr>